import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"], weights: [400, 500, 600, 700, 900] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />

        <Script src="https://www.google.com/recaptcha/api.js" />
      </body>
    </html>
  );
}
